### PR TITLE
Adds extraParams to openUrl to allow rich object passing

### PR DESCRIPTION
**Pull request by NorthStar**
Through routing when a controller opens an url.

### CODE REVIEW

**Comment by sweetverbs** [comment]
Hi @clayallsopp, I've written tests for @NorthStar's changes. Would you like me to submit a new pull request?

**Comment by NorthStar** [comment]
Thanks! Sorry that schooling got in my way.

**Comment by jrmiddle** [comment]
Hi all, any update on this?

**Comment by sweetverbs** [comment]
I pushed the tests to my fork of Routable. I also updated the tests from SenTest to XCTest and fixed a bug which meant that the rich object params weren't working properly when a different object was sent to the same URL.

In the process I discovered [this issue](https://github.com/clayallsopp/routable-ios/issues/35) which I'm currently trying to work out a fix for. I'm hesitant to make a pull request while there are still failing tests.

**Comment by clayallsopp** [comment]
@sweetverbs @NorthStar thanks for digging into these problems - I'm totally happy to look at any PR/one of your fork

**Pull request merged**
